### ISSUE TITLE
JOSE Checklist

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis_data#5]
Review checklist 

**Conflict of interest**

- [ ]  As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/joss/blob/jose/COI.md) and that there are no conflicts of interest for me to review this work.

**Code of Conduct**

- [ ]  I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

**General checks**

 

- [ ] Repository: Is the source for this learning module available at the [repository url](https://gitlab.eumetsat.int/eumetlab/atmosphere/atmosphere)?

 

- [ ] License: Does the repository contain a plain-text LICENSE file with the contents of a standard license? (OSI-approved for code, Creative Commons for content)

 

- [ ] Version: Does the release version given match the repository release (v0.5)?

 

- [ ] Authorship: Has the submitting author (@jwagemann) made visible contributions to the module? Does the full list of authors seem appropriate and complete?

**Documentation**

- [ ]  A statement of need: Do the authors clearly state the need for this module and who the target audience is?

- [ ]  Installation instructions: Is there a clearly stated list of dependencies?

- [ ]  Usage: Does the documentation explain how someone would adopt the module, and include examples of how to use it?

 

- [ ] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

**Pedagogy / Instructional design (Work-in-progress: reviewers, please comment!)**

- [ ]  Learning objectives: Does the module make the learning objectives plainly clear? (We don't require explicitly written learning objectives; only that they be evident from content and design.)

 

- [ ] Content scope and length: Is the content substantial for learning a given topic? Is the length of the module appropriate?

 

- [ ] Pedagogy: Does the module seem easy to follow? Does it observe guidance on cognitive load? (working memory limits of 7 +/- 2 chunks of information)

- [ ]  Content quality: Is the writing of good quality, concise, engaging? Are the code components well crafted? Does the module seem complete?

- [ ]  Instructional design: Is the instructional design deliberate and apparent? For example, exploit worked-example effects; effective multi-media use; low extraneous cognitive load.

- [ ] JOSE paper

- [ ]  Authors: Does the paper.md file include a list of authors with their affiliations?

- [ ]  A statement of need: Does the paper clearly state the need for this module and who the target audience is?

- [ ]  Description: Does the paper describe the learning materials and sequence?

 

- [ ] Does it describe how it has been used in the classroom or other settings, and how someone might adopt it?

- [ ]  Could someone else teach with this module, given the right expertise?

 

- [ ] Does the paper tell the "story" of how the authors came to develop it, or what their expertise is?

- [ ]  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by AlexanderJuestel** [comment]
Repository: Is the source for this learning module available at the [repository url](https://github.com/cgre-aachen/gemgis_data)?

The repository is available at the following URL: https://github.com/cgre-aachen/gemgis_data

**Comment by AlexanderJuestel** [comment]
License: Does the repository contain a plain-text LICENSE file with the contents of a standard license? (OSI-approved for code, Creative Commons for content)

The Licence can be found here: https://github.com/cgre-aachen/gemgis_data/blob/main/LICENSE

**Comment by AlexanderJuestel** [comment]
Version: Does the release version given match the repository release (v0.5)?

The release version will be **v0.1** upon submitting the paper

**Comment by AlexanderJuestel** [comment]
Authorship: Has the submitting author (@AlexanderJuestel ) made visible contributions to the module? Does the full list of authors seem appropriate and complete?

Yes, @AlexanderJuestel has made visible contributions. The full list of authors include most of the GemPy and GemGIS authors

![image](https://user-images.githubusercontent.com/45469915/163770212-fb2ce46e-3457-4764-b326-7740c3c8ec8b.png)

**Comment by AlexanderJuestel** [comment]
A statement of need: Do the authors clearly state the need for this module and who the target audience is?

Yes, need is stated to explore the subsurface and target audience are students people interested in Geomodeling.
![image](https://user-images.githubusercontent.com/45469915/163776639-26775291-27c6-47ac-b49f-273a79d140cc.png)

**Comment by AlexanderJuestel** [comment]
Installation instructions: Is there a clearly stated list of dependencies?

The data repository mainly depends on GemGIS and GemPy. Their installation and documentation are linked in the readme 

![image](https://user-images.githubusercontent.com/45469915/163776868-7a27f25a-4f8b-4fc5-99c5-0ade04a4d273.png)

**Comment by AlexanderJuestel** [comment]
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

The link to the Contribution/Community Guidelines is here: https://github.com/cgre-aachen/gemgis_data/blob/main/CONTRIBUTING.md

**Comment by AlexanderJuestel** [comment]
Authors: Does the paper.md file include a list of authors with their affiliations?

Yes 

![image](https://user-images.githubusercontent.com/45469915/163778898-c6eea76d-5310-4e9d-9731-2fd3da34bcba.png)
